all:
  hosts:
    node-1:
      ansible_host: 81.200.150.220
      ansible_user: root
      ip: 10.0.0.4
    node-2:
      ansible_host: 81.200.150.247
      ansible_user: root
      ip: 10.0.0.5
    node-3:
      ansible_host: 81.200.151.17
      ansible_user: root
      ip: 10.0.0.6
  children:
    kube_control_plane:
      hosts:
        node-1:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
    etcd:
      hosts:
        node-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: