all:
  hosts:
    node-1:
      ansible_host: 1.1.1.1
      ip: 10.0.0.4
    node-2:
      ansible_host: 1.1.1.2
      ip: 10.0.0.5
    node-3:
      ansible_host: 1.1.1.3
      ip: 10.0.0.6
  children:
    kube_control_plane:
      hosts:
        node-1:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
    etcd:
      hosts:
        node-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: