all:
  hosts:
    node-1:
      ansible_host: 1.1.1.1 # IP address that Ansible can connect to
      ip: 10.0.0.4 # IP address that the node will advertise
    node-2:
      ansible_host: 1.1.1.2
      ip: 10.0.0.5
    node-3:
      ansible_host: 1.1.1.3
      ip: 10.0.0.6
  children:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
    k8s_cluster:
      children:
        kube_node: